name: Firebase Deploy

on:
  push:
    branches:
      - master

env:
  REACT_APP_WEATHER_KEY: ${{ secrets.REACT_APP_WEATHER_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm ci
      - run: npm run build
        env:
          CI: false
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
